spring:
  application:
    name: ObjectStorage
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  data:
    redis:
      host: localhost
      port: 6864

    jpa:
      hibernate:
        ddl-auto: create

jwt:
  secret: ${JWT_SECRET}
